function [xans] = CubicLagrange(X_values, Y_values, x_val)
x = sym('x');
expression = (((x - X_values(2)) * (x - X_values(3)) * (x - X_values(4))) / ...
    ((X_values(1) - X_values(2)) * (X_values(1) - X_values(3)) * (X_values(1) - X_values(4))) * Y_values(1)) + ...
    (((x - X_values(1)) * (x - X_values(3)) * (x - X_values(4))) / ...
    ((X_values(2) - X_values(1)) * (X_values(2) - X_values(3)) * (X_values(2) - X_values(4))) * Y_values(2)) + ...
    (((x - X_values(1)) * (x - X_values(2)) * (x - X_values(4))) / ...
    ((X_values(3) - X_values(1)) * (X_values(3) - X_values(2)) * (X_values(3) - X_values(4))) * Y_values(3)) + ...
    (((x - X_values(1)) * (x - X_values(2)) * (x - X_values(3))) / ...
    ((X_values(4) - X_values(1)) * (X_values(4) - X_values(2)) * (X_values(4) - X_values(3))) * Y_values(4));

disp(expression);
xans = double(subs(expression, x, x_val));
end
